---
# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.50
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable ota
ota:
  password: !secret ota_password

# Enable logging
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

esphome:
  name: smartmeter
  platform: ESP8266
  board: d1_mini
  includes:
    - custom-components/dsmr_mqtt.h

sensor:
  - platform: custom
    lambda: |-
      auto dsmr_mqtt = new DsmrMqtt();
      App.register_component(dsmr_mqtt);
      return {
        dsmr_mqtt->consumption_low_tarif,
        dsmr_mqtt->consumption_high_tarif,
        dsmr_mqtt->production_low_tarif,
        dsmr_mqtt->production_high_tarif,
        dsmr_mqtt->power_delivered,
        dsmr_mqtt->power_received,
        dsmr_mqtt->instant_power_usage,
        dsmr_mqtt->instant_power_current,
        dsmr_mqtt->gas_meter_m3,
        dsmr_mqtt->actual_tarif_group,
        dsmr_mqtt->short_power_outages,
        dsmr_mqtt->long_power_outages,
        dsmr_mqtt->short_power_drops,
        dsmr_mqtt->short_power_peaks
      };
    sensors:
      - name: Power consumption low
        unit_of_measurement: kWh
        accuracy_decimals: 3
        on_value:
          then:
            - switch.turn_on: led
            - delay: 100ms
            - switch.turn_off: led
      - name: Power consumption normal
        unit_of_measurement: kWh
        accuracy_decimals: 3
      - name: Power production low
        unit_of_measurement: kWh
        accuracy_decimals: 3
      - name: Power production normal
        unit_of_measurement: kWh
        accuracy_decimals: 3
      - name: Actual consumption
        unit_of_measurement: kWh
        accuracy_decimals: 3
      - name: Instant power usage
        unit_of_measurement: kWh
        accuracy_decimals: 3
      - name: Instant power current
        unit_of_measurement: A
        accuracy_decimals: 3
      - name: Gas consumption
        unit_of_measurement: m3
        accuracy_decimals: 3
      - name: Tarif group
      - name: Short power outages
      - name: Long power outages
      - name: Short power drops
      - name: Short power peaks

switch:
  - platform: gpio
    pin: D5
    id: led
