---
# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.52
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable ota
ota:
  password: !secret ota_password

# Enable logging
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

# Esphome setup
esphome:
  name: tv_remote
  platform: ESP8266
  board: d1_mini

# Receive codes
# remote_receiver:
#   pin:
#     number: D6
#     inverted: True
#   dump: all

remote_transmitter:
  pin:
    number: D7
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: TV Power Button
    icon: "mdi:television"
    optimistic: true  # Needed to trace on/off in hass
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
    turn_off_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF

  - platform: template
    name: TV Source Button
    icon: "mdi:television-guide"
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0807F
