---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.53
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
  password: !secret ota_password

esphome:
  name: bedroom_blind
  platform: ESP8266
  board: nodemcu

stepper:
- platform: uln2003
  id: bedroom_blind
  pin_a: D0
  pin_b: D1
  pin_c: D2
  pin_d: D3
  max_speed: 100 steps/s

  acceleration: 10
  deceleration: 10

cover:
- platform: template
  device_class: blind
  name: "Bedroom Blind"
  assumed_state: true
  open_action:
  - stepper.set_target:
      id: bedroom_blind
      target: 0
  close_action:
  - stepper.set_target:
      id: bedroom_blind
      target: 250
