---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.53
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
  password: !secret ota_password

esphome:
  name: bedroom_blind
  platform: ESP8266
  board: d1

stepper:
- platform: uln2003
  id: bedroom_blind
  # NOTE: Does not seem to work on other ports
  pin_a: D8
  pin_b: D7
  pin_c: D6
  pin_d: D5
  max_speed: 1000 steps/s
  acceleration: 10
  deceleration: 10
  sleep_when_done: true

cover:
- platform: template
  device_class: blind
  name: "Bedroom Blind"
  open_action:
    - stepper.set_target:
        id: bedroom_blind
        target: 0
  close_action:
    - stepper.set_target:
        id: bedroom_blind
        target: 25000
  stop_action:
    - stepper.set_target:
        id: bedroom_blind
        target: !lambda return id(bedroom_blind).current_position;
