---
# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.54
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable ota
ota:
  password: !secret ota_password

# Enable logging
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

# Esphome setup
esphome:
  name: kitchen_light
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Sonoff Basic Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Sonoff Basic Relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
