---
# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.55
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable ota
ota:
  password: !secret ota_password

# Enable logging
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

# Enable esphome
esphome:
  name: watermeter
  platform: ESP8266
  board: d1_mini

sensor:
  - platform: pulse_counter
    pin:
      number: D1
      # mode: INPUT_PULLUP
    name: Water Meter
    unit_of_measurement: m3
    update_interval: 10s
    # internal_filter: 5us
    # filters:
    #   - multiply: 0.006  # 10000/min = 1m3
    accuracy_decimals: 4
    on_value:
      then:
        - switch.turn_on: led
        - delay: 100ms
        - switch.turn_off: led

switch:
  - platform: gpio
    pin: D5
    id: led
