---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
  password: !secret ota_password

esphome:
  name: watermeter
  platform: ESP8266
  board: d1

sensor:
  - platform: pulse_counter
    pin: D1
    name: Water Meter
    unit_of_measurement: m3
    internal_filter: 10us
    filters:
      - multiply: 0.006  # 10000/min = 1m3
    on_value:
      then:
        - switch.toggle: led

switch:
  - platform: gpio
    pin: D5
    id: led
