---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  services:
      - service: bedroom_blinds_control
        variables:
          target: int
        then:
          - stepper.set_target:
              id: bedroom_blinds
              target: !lambda 'return target;'

ota:
  password: !secret ota_password

esphome:
  name: bedroom-blinds
  platform: ESP8266
  board: nodemcu

stepper:
  - platform: uln2003
    id: bedroom_blinds
    pin_a: D0
    pin_b: D1
    pin_c: D2
    pin_d: D3
    max_speed: 100 steps/s

    acceleration: 10
    deceleration: 10
