---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.52
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
  password: !secret ota_password

esphome:
  name: tv_remote
  platform: ESP8266
  board: d1

# Receive codes
# remote_receiver:
#   pin:
#     number: D6
#     inverted: True
#   dump: all

switch:
  - platform: template
    name: TV Power Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF

switch:
  - platform: template
    name: TV Source Button
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0807F
